--DROP TABLES
DROP TABLE APP.SPECIALS;

DROP TABLE APP.INGREDIENTS;

DROP TABLE APP.INVENTORY;

DROP TABLE APP.ORDER_DETAILS;

DROP TABLE APP.PRODUCTS;

DROP TABLE APP.ORDERS;



------------------------------------------------------------------------------------------


--TABLE INVENTORY
CREATE TABLE APP.INVENTORY (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SUPPLIER_PRODUCT_ID VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL CONSTRAINT INVENTORY_DESCRIPTION_UK UNIQUE,	
	QUANTITY FLOAT NOT NULL DEFAULT 0,
    UNIT VARCHAR(5) NOT NULL,
    RESTOCKING_LEVEL FLOAT NOT NULL DEFAULT 0,
    RESTOCKING_QUANTITY FLOAT NOT NULL DEFAULT 0,
    CONSTRAINT INVENTORY_PK PRIMARY KEY (ID)
);

--ADD SOME DATA
INSERT INTO TABLE APP.INVENTORY
(SUPPLIER_PRODUCT_ID,DESCRIPTION,QUANTITY,UNIT,RESTOCKING_LEVEL,RESTOCKING_QUANTITY)
VALUES('SKU-ABC1231254', 'HARINA',50, 'LB', 10, 0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12341', 'Harina de trigo', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12341', 'Harina de trigo1', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12343', 'Harina de trigo3', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12344', 'Harina de trigo4', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12345', 'Harina de trigo5', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12346', 'Harina de trigo6', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12347', 'Harina de trigo7', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12348', 'Harina de trigo8', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-12349', 'Harina de trigo9', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123410', 'Harina de trigo10', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123411', 'Harina de trigo11', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123412', 'Harina de trigo12', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123413', 'Harina de trigo13', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123414', 'Harina de trigo14', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123415', 'Harina de trigo15', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123416', 'Harina de trigo16', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123417', 'Harina de trigo17', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123418', 'Harina de trigo18', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123419', 'Harina de trigo19', 100.0, 'LB', 10.0, 0.0);
INSERT INTO APP.INVENTORY (SUPPLIER_PRODUCT_ID, DESCRIPTION, QUANTITY, UNIT, RESTOCKING_LEVEL, RESTOCKING_QUANTITY) VALUES ('SKU-123420', 'Harina de trigo20', 100.0, 'LB', 10.0, 0.0);


--TABLE PRODUCTS
CREATE TABLE APP.PRODUCTS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL CONSTRAINT PRODUCTS_NAME_UK UNIQUE,
    DESCRIPTION VARCHAR(300) NOT NULL,
	PRICE NUMERIC(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (ID)
);

INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO1', 'ESTE PRODUCTO ES DE ORIGEN .....1', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO2', 'ESTE PRODUCTO ES DE ORIGEN .....2', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO3', 'ESTE PRODUCTO ES DE ORIGEN .....3', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO4', 'ESTE PRODUCTO ES DE ORIGEN .....4', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO5', 'ESTE PRODUCTO ES DE ORIGEN .....5', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO6', 'ESTE PRODUCTO ES DE ORIGEN .....6', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO7', 'ESTE PRODUCTO ES DE ORIGEN .....7', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO8', 'ESTE PRODUCTO ES DE ORIGEN .....8', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO9', 'ESTE PRODUCTO ES DE ORIGEN .....9', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO10', 'ESTE PRODUCTO ES DE ORIGEN .....10', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO11', 'ESTE PRODUCTO ES DE ORIGEN .....11', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO12', 'ESTE PRODUCTO ES DE ORIGEN .....12', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO13', 'ESTE PRODUCTO ES DE ORIGEN .....13', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO14', 'ESTE PRODUCTO ES DE ORIGEN .....14', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO15', 'ESTE PRODUCTO ES DE ORIGEN .....15', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO16', 'ESTE PRODUCTO ES DE ORIGEN .....16', 20.00);
INSERT INTO APP.PRODUCTS ("NAME", DESCRIPTION, PRICE) VALUES ('QUIPE DE QUESO17', 'ESTE PRODUCTO ES DE ORIGEN .....17', 20.00);


--TABLE INGREDIENTES
CREATE TABLE APP.INGREDIENTS (
    PRODUCT_ID INTEGER NOT NULL CONSTRAINT INGREDIENTS_PRODUCT_FK REFERENCES APP.PRODUCTS,
    INVENTORY_ID INTEGER NOT NULL CONSTRAINT INVENTORY_PRODUCT_FK REFERENCES APP.INVENTORY,
    QUANTITY_NEEDED FLOAT NOT NULL CONSTRAINT INGREDIENTS_QUANTITY_CK CHECK (QUANTITY_NEEDED > 0),
    CONSTRAINT INGREDIENTS_PK PRIMARY KEY (PRODUCT_ID, INVENTORY_ID)
);

--CREATE SOME DATA
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (4, 10, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (5, 11, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (6, 12, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (7, 13, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (8, 14, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (9, 15, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (10, 16, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (11, 17, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (12, 18, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (13, 19, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (14, 20, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (15, 21, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (16, 22, 10.0);
INSERT INTO APP.INGREDIENTS (PRODUCT_ID, INVENTORY_ID, QUANTITY_NEEDED) VALUES (17, 23, 10.0);


--TABLE ORDERS
CREATE TABLE APP.ORDERS (
  order_no BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  email VARCHAR(50),
  customer_name VARCHAR(100),
  address varchar(200) not null,
  phone   varchar(20),
  CONSTRAINT orders_pk PRIMARY KEY (order_no)

);

INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);
INSERT INTO APP.ORDERS (EMAIL, CUSTOMER_NAME, ADDRESS, PHONE) VALUES (NULL, 'Frederick Clark', 'c/ El establo,# 26, Bello Campo, Santo Domingo Este', NULL);



--TABLE ORDER_DETAILS
CREATE TABLE APP.ORDER_DETAILS (
  ORDER_NO BIGINT NOT NULL CONSTRAINT ORDER_FK REFERENCES APP.ORDERS,
  PRODUCT_ID INTEGER NOT NULL CONSTRAINT ORDER_DET_PRODUCT_FK REFERENCES APP.PRODUCTS,
  DETAIL_SEQ SMALLINT NOT NULL,
  QUANTITY SMALLINT NOT NULL CONSTRAINT ORDER_DET_QUANTITY_CK CHECK (QUANTITY > 0),
  CONSTRAINT order_det_pk PRIMARY KEY (ORDER_NO, PRODUCT_ID)
);

INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 2, 1, 3);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 3, 2, 6);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 4, 3, 9);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 5, 4, 12);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 6, 5, 15);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 7, 6, 18);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 8, 7, 21);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 9, 8, 24);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 10, 9, 27);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 11, 10, 30);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 12, 11, 33);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 13, 12, 36);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 14, 13, 39);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (8, 15, 14, 42);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 2, 1, 3);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 3, 2, 6);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 4, 3, 9);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 5, 4, 12);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 6, 5, 15);
INSERT INTO APP.ORDER_DETAILS (ORDER_NO, PRODUCT_ID, DETAIL_SEQ, QUANTITY) VALUES (9, 7, 6, 18);


--TABLE SPECIALS
CREATE TABLE APP.SPECIALS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DESCRIPTION VARCHAR(140) NOT NULL,
    SUMMARY VARCHAR(1000),
    CREATION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    EXPIRATION_DATE DATE,
    CONSTRAINT SPECIALS_PK PRIMARY KEY (ID)
);